default: &default
  adapter:  postgresql
  host:     <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port:     <%= ENV['POSTGRES_PORT'] || 5432 %>
  pool:     <%= ENV['POSTGRES_POOL'] || 5 %>
  encoding: unicode
  username: <%= ENV['POSTGRES_USERNAME'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'postgres' %>


development:
  <<: *default
  database: feature_flag_server_dev

test:
  <<: *default
  database: feature_flag_server_test

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'feature_flag_server_production' %>
